### ISSUE TITLE
Can not load the webpage of GoogleDrive for model downloading

### ISSUE THREAD

**Issue by henryham** [EvelynFan/DSN#1]
Hi, Evelyn. I found the webaddress you put on to download your models seems doesn't work. Where can I download you models ?

**Comment by EvelynFan** [comment]
Hi, Henry, now the link should work.

**Comment by EvelynFan** [comment]
> Hi, Evelyn. I found the webaddress you put on to download your models seems doesn't work. Where can I download you models ?

Hi, Henry, now the link should work.

**Comment by henryham** [comment]
> > Hi, Evelyn. I found the webaddress you put on to download your models seems doesn't work. Where can I download you models ?
> 
> Hi, Henry, now the link should work.

Thanks a lot!
